[project]
name = "pysl"
version = "0.1.0"
description = "Add a short description here"
authors = ["raceychan <raceychan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pybind11 = ">=2.11.1,<2.12"
